name: Docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ prereleased, released ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'maven'
      - name: Run Java tests
        run: mvn test
      - name: Persist Java tests reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test reports
          path: |
            gtfs-realtime-validator-lib/target/surefire-reports
            gtfs-realtime-validator-webapp/target/surefire-reports
  build_push:
    needs: test
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'maven'
      - name: Package cli app jar with Maven
        run: mvn package
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT_GTFS_RT_VALIDATOR }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          labels: |
            org.opencontainers.image.source=https://github.com/mobilitydata/gtfs-realtime-validator.git
            org.opencontainers.image.revision=${{ github.sha }}
# should be org.opencontainers.image.source=${{ github.event.repository.clone_url }} but caps in MobilityData seem to break something
