name: Test Package

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  release:
    types: [ prereleased, released ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'maven'
      - name: Run Java tests
        run: mvn test
      - name: Persist Java tests reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test reports
          path: |
            gtfs-realtime-validator-lib/target/surefire-reports
            gtfs-realtime-validator-webapp/target/surefire-reports
  pack:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'maven'
      - name: Package cli app jar with Maven
        run: mvn package -DskipTests
      - name: Persist lib jar
        uses: actions/upload-artifact@v2
        with:
          name: gtfs-realtime-validator-lib-1.0.0-SNAPSHOT.jar
          path: gtfs-realtime-validator-lib/target/gtfs-realtime-validator-lib-1.0.0-SNAPSHOT.jar
      - name: Persist webapp jar
        uses: actions/upload-artifact@v2
        with:
          name: gtfs-realtime-validator-webapp-1.0.0-SNAPSHOT.jar
          path: gtfs-realtime-validator-webapp/target/gtfs-realtime-validator-webapp-1.0.0-SNAPSHOT.jar
